const students = [
  {
    id: 1,
    name: "Abdul Mubeen",
    rating: 4.6,
    tag: "Popular",
    price: "£6",
    college: "Surrey University",
    classof: "Class of 2026",
    placed: "Placed at Microsoft",
    duration: "30 mins",
    title: "1:1 Mentorship",
    description:
      "Got questions about coding, placements, or which path to choose? Book a 1:1 call with me. I'll personally guide you based on your background.",
    cta: "Book Now – Limited slots every week",
    avatar: "https://i.pravatar.cc/150?img=12",
    testimonials: [
      { name: "Vukkalkar Chethana", review: "Helpful and good", avatar: "V" },
      { name: "Meghana", review: "Good explanation", avatar: "M" },
      { name: "Rahul Sharma", review: "Very insightful session!", avatar: "R" },
      { name: "Priya K", review: "Cleared all my doubts", avatar: "P" },
    ],
  },
  {
    id: 2,
    name: "Manoj Dusari",
    rating: 4.6,
    tag: "Popular",
    price: "£6",
    college: "Surrey University",
    classof: "Class of 2026",
    placed: "Placed at Microsoft",
    duration: "30 mins",
    title: "1:1 Mentorship",
    description:
      "Got questions about coding, placements, or which path to choose? Book a 1:1 call with me. I'll personally guide you based on your background.",
    cta: "Book Now – Limited slots every week",
    avatar: "https://i.pravatar.cc/150?img=12",
    testimonials: [
      { name: "Vukkalkar Chethana", review: "Helpful and good", avatar: "V" },
      { name: "Meghana", review: "Good explanation", avatar: "M" },
      { name: "Rahul Sharma", review: "Very insightful session!", avatar: "R" },
      { name: "Priya K", review: "Cleared all my doubts", avatar: "P" },
    ],
  },
  {
    id: 3,
    name: "Niaz Ahmed",
    rating: 4.6,
    tag: "Popular",
    price: "£6",
    college: "Surrey University",
    classof: "Class of 2026",
    placed: "Placed at Microsoft",
    duration: "30 mins",
    title: "1:1 Mentorship",
    description:
      "Got questions about coding, placements, or which path to choose? Book a 1:1 call with me. I'll personally guide you based on your background.",
    cta: "Book Now – Limited slots every week",
    avatar: "https://i.pravatar.cc/150?img=12",
    testimonials: [
      { name: "Vukkalkar Chethana", review: "Helpful and good", avatar: "V" },
      { name: "Meghana", review: "Good explanation", avatar: "M" },
      { name: "Rahul Sharma", review: "Very insightful session!", avatar: "R" },
      { name: "Priya K", review: "Cleared all my doubts", avatar: "P" },
    ],
  },
  {
    id: 4,
    name: "Manideep Chitimodu",
    rating: 4.6,
    tag: "Popular",
    price: "£6",
    college: "Surrey University",
    classof: "Class of 2026",
    placed: "Placed at Microsoft",
    duration: "30 mins",
    title: "1:1 Mentorship",
    description:
      "Got questions about coding, placements, or which path to choose? Book a 1:1 call with me. I'll personally guide you based on your background.",
    cta: "Book Now – Limited slots every week",
    avatar: "https://i.pravatar.cc/150?img=12",
    testimonials: [
      { name: "Vukkalkar Chethana", review: "Helpful and good", avatar: "V" },
      { name: "Meghana", review: "Good explanation", avatar: "M" },
      { name: "Rahul Sharma", review: "Very insightful session!", avatar: "R" },
      { name: "Priya K", review: "Cleared all my doubts", avatar: "P" },
    ],
  },
  {
    id: 5,
    name: "Sandeep Kalasala",
    rating: 4.6,
    tag: "Popular",
    price: "£6",
    college: "Surrey University",
    classof: "Class of 2026",
    placed: "Placed at Microsoft",
    duration: "30 mins",
    title: "1:1 Mentorship",
    description:
      "Got questions about coding, placements, or which path to choose? Book a 1:1 call with me. I'll personally guide you based on your background.",
    cta: "Book Now – Limited slots every week",
    avatar: "https://i.pravatar.cc/150?img=12",
    testimonials: [
      { name: "Vukkalkar Chethana", review: "Helpful and good", avatar: "V" },
      { name: "Meghana", review: "Good explanation", avatar: "M" },
      { name: "Rahul Sharma", review: "Very insightful session!", avatar: "R" },
      { name: "Priya K", review: "Cleared all my doubts", avatar: "P" },
    ],
  },
  {
    id: 6,
    name: "Sreya Gonela",
    rating: 4.6,
    tag: "Popular",
    price: "£6",
    college: "Surrey University",
    classof: "Class of 2026",
    placed: "Placed at Microsoft",
    duration: "30 mins",
    title: "1:1 Mentorship",
    description:
      "Got questions about coding, placements, or which path to choose? Book a 1:1 call with me. I'll personally guide you based on your background.",
    cta: "Book Now – Limited slots every week",
    avatar: "https://i.pravatar.cc/150?img=12",
    testimonials: [
      { name: "Vukkalkar Chethana", review: "Helpful and good", avatar: "V" },
      { name: "Meghana", review: "Good explanation", avatar: "M" },
      { name: "Rahul Sharma", review: "Very insightful session!", avatar: "R" },
      { name: "Priya K", review: "Cleared all my doubts", avatar: "P" },
    ],
  },
  {
    id: 7,

    name: "Jyoshna jagati",
    rating: 4.6,
    tag: "Popular",
    price: "£6",
    college: "Surrey University",
    classof: "Class of 2026",
    placed: "Placed at Microsoft",
    duration: "30 mins",
    title: "1:1 Mentorship",
    description:
      "Got questions about coding, placements, or which path to choose? Book a 1:1 call with me. I'll personally guide you based on your background.",
    cta: "Book Now – Limited slots every week",
    avatar: "https://i.pravatar.cc/150?img=12",
    testimonials: [
      { name: "Vukkalkar Chethana", review: "Helpful and good", avatar: "V" },
      { name: "Meghana", review: "Good explanation", avatar: "M" },
      { name: "Rahul Sharma", review: "Very insightful session!", avatar: "R" },
      { name: "Priya K", review: "Cleared all my doubts", avatar: "P" },
    ],
  },
  {
    id: 8,
    name: "Abdul Mubeen",
    rating: 4.6,
    tag: "Popular",
    price: "£6",
    college: "Surrey University",
    classof: "Class of 2026",
    placed: "Placed at Microsoft",
    duration: "30 mins",
    title: "1:1 Mentorship",
    description:
      "Got questions about coding, placements, or which path to choose? Book a 1:1 call with me. I'll personally guide you based on your background.",
    cta: "Book Now – Limited slots every week",
    avatar: "https://i.pravatar.cc/150?img=12",
    testimonials: [
      { name: "Vukkalkar Chethana", review: "Helpful and good", avatar: "V" },
      { name: "Meghana", review: "Good explanation", avatar: "M" },
      { name: "Rahul Sharma", review: "Very insightful session!", avatar: "R" },
      { name: "Priya K", review: "Cleared all my doubts", avatar: "P" },
    ],
  },
  {
    id: 9,
    name: "Abdul Mubeen",
    rating: 4.6,
    tag: "Popular",
    price: "£6",
    college: "Surrey University",
    classof: "Class of 2026",
    placed: "Placed at Microsoft",
    duration: "30 mins",
    title: "1:1 Mentorship",
    description:
      "Got questions about coding, placements, or which path to choose? Book a 1:1 call with me. I'll personally guide you based on your background.",
    cta: "Book Now – Limited slots every week",
    avatar: "https://i.pravatar.cc/150?img=12",
    testimonials: [
      { name: "Vukkalkar Chethana", review: "Helpful and good", avatar: "V" },
      { name: "Meghana", review: "Good explanation", avatar: "M" },
      { name: "Rahul Sharma", review: "Very insightful session!", avatar: "R" },
      { name: "Priya K", review: "Cleared all my doubts", avatar: "P" },
    ],
  },
  {
    id: 10,
    name: "Abdul Mubeen",
    rating: 4.6,
    tag: "Popular",
    price: "£6",
    college: "Surrey University",
    classof: "Class of 2026",
    placed: "Placed at Microsoft",
    duration: "30 mins",
    title: "1:1 Mentorship",
    description:
      "Got questions about coding, placements, or which path to choose? Book a 1:1 call with me. I'll personally guide you based on your background.",
    cta: "Book Now – Limited slots every week",
    avatar: "https://i.pravatar.cc/150?img=12",
    testimonials: [
      { name: "Vukkalkar Chethana", review: "Helpful and good", avatar: "V" },
      { name: "Meghana", review: "Good explanation", avatar: "M" },
      { name: "Rahul Sharma", review: "Very insightful session!", avatar: "R" },
      { name: "Priya K", review: "Cleared all my doubts", avatar: "P" },
    ],
  },
  {
    id: 11,
    name: "Abdul Mubeen",
    rating: 4.6,
    tag: "Popular",
    price: "£6",
    college: "Surrey University",
    classof: "Class of 2026",
    placed: "Placed at Microsoft",
    duration: "30 mins",
    title: "1:1 Mentorship",
    description:
      "Got questions about coding, placements, or which path to choose? Book a 1:1 call with me. I'll personally guide you based on your background.",
    cta: "Book Now – Limited slots every week",
    avatar: "https://i.pravatar.cc/150?img=12",
    testimonials: [
      { name: "Vukkalkar Chethana", review: "Helpful and good", avatar: "V" },
      { name: "Meghana", review: "Good explanation", avatar: "M" },
      { name: "Rahul Sharma", review: "Very insightful session!", avatar: "R" },
      { name: "Priya K", review: "Cleared all my doubts", avatar: "P" },
    ],
  },
];

export default students;
